apiVersion: batch/v1
kind: Job
metadata:
  name: load-federation-test-data
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: adapter
          image: "docker.io/bitnami/kafka:3.8.0-debian-12-r2"
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP_VALUE
              value: override.with.bootstrap.servers
          command:
            - sh
            - -c
          args:
            - |-
              set -eu
              kafka-console-producer.sh \
              --bootstrap-server "$BOOTSTRAP_VALUE" \
              --topic knowledge \
              --producer.config=/app/config/kafka-auth/kafka-config.properties \
              --property parse.headers=true \
              --property headers.separator=";" < /data/test.dat
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - mountPath: /app/config/kafka-auth/
              name: kafka-auth-config
      volumes:
        - name: data-volume
          configMap:
            name: "test-data"
        - name: kafka-auth-config
          secret:
            secretName: kafka-auth-config
