apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/from/0/source/principals/0
        value: "cluster.local/ns/istio-system/sa/PROVIDE.GATEWAY.SERVICE.ACCOUNT.IDENTITY"
    target:
      kind: AuthorizationPolicy
      name: allow-ingress-to-federation-server
