apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/from/0/source/principals/0
        value: "override.ingress.principal"
    target:
      kind: AuthorizationPolicy
      name: allow-ingress-to-federation-server
