#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Defines the virtual service host used for the istio configuration
# Using this component will patch VirtualServices resources to the same host value,
# filtered by defined resource names
patches:
  # Core apps - Access
  - path: patch/host.yaml
    target:
      kind: VirtualService
      name: oidc-login-ingress|access-ui-ingress|access|query-ui-ingress
  # Core apps - Graph
  - path: patch/host.yaml
    target:
      kind: VirtualService
      name: graph-server-ingress
