#
# Copyright (C) 2024 Telicent Limited
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tc-graph

secretGenerator:
  - name: kafka-auth-config
    files:
      - secret/kafka-config.properties
    options:
      disableNameSuffixHash: true
